// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB20UmsoI1DIne0CDC-n9NSNf6_zt-MiXY',
    appId: '1:674648400625:web:1bc13a4d92f0a4f75abf50',
    messagingSenderId: '674648400625',
    projectId: 'oralscope-78cda',
    authDomain: 'oralscope-78cda.firebaseapp.com',
    storageBucket: 'oralscope-78cda.firebasestorage.app',
    measurementId: 'G-XM74GVJ4HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSALib5E6zdjr7dajIAEXohnuDvfzzY8Q',
    appId: '1:674648400625:android:338a07fc0d9b3be65abf50',
    messagingSenderId: '674648400625',
    projectId: 'oralscope-78cda',
    storageBucket: 'oralscope-78cda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_0HFj63xTlXYO_M9xudMg753RfXI7_M',
    appId: '1:674648400625:ios:24f8c2c74a078c375abf50',
    messagingSenderId: '674648400625',
    projectId: 'oralscope-78cda',
    storageBucket: 'oralscope-78cda.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicStaffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_0HFj63xTlXYO_M9xudMg753RfXI7_M',
    appId: '1:674648400625:ios:24f8c2c74a078c375abf50',
    messagingSenderId: '674648400625',
    projectId: 'oralscope-78cda',
    storageBucket: 'oralscope-78cda.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicStaffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUSyugIk8UBdG4TaE2FkWNeacPERtpv0',
    appId: '1:674648400625:web:21fe9d9f94f729c25abf50',
    messagingSenderId: '674648400625',
    projectId: 'oralscope-78cda',
    authDomain: 'oralscope-78cda.firebaseapp.com',
    storageBucket: 'oralscope-78cda.firebasestorage.app',
    measurementId: 'G-FN9FFVMX60',
  );
}
